import { authenticatedFetch } from './apiAuth.ts';
import { AccountDataApiError } from '../types/accountData.ts';
import type { AccountDataSnapshot, CashFlowDraft, ManualAccountDraft, OpeningHoldingDraft } from '../types/accountData.ts';
const route = '/api/nsdl/account-data';
export const createAccountDataIdempotencyKey = (): string => crypto.randomUUID();
async function responseBody(response: Response): Promise<any> { let body: any = null; try { body = await response.json(); } catch { /* fixed fallback */ } if (!response.ok) throw new AccountDataApiError(typeof body?.detail === 'string' ? body.detail : 'ERR_ACCOUNT_REQUEST_INVALID', response.status); return body; }
export async function fetchAccountData(portfolioId: string, signal?: AbortSignal): Promise<AccountDataSnapshot> { const body = await responseBody(await authenticatedFetch(`${route}?portfolio_id=${encodeURIComponent(portfolioId)}`, { method: 'GET', signal, headers: { Accept: 'application/json' } })); if (!body || !Array.isArray(body.accounts) || !Array.isArray(body.openingHoldings) || !Array.isArray(body.cashFlows)) throw new AccountDataApiError('ERR_ACCOUNT_REQUEST_INVALID', 400); return body as AccountDataSnapshot; }
async function post(path: string, portfolioId: string, payload: Record<string, unknown>, signal?: AbortSignal, key = createAccountDataIdempotencyKey()): Promise<any> { return responseBody(await authenticatedFetch(`${route}/${path}?portfolio_id=${encodeURIComponent(portfolioId)}`, { method: 'POST', signal, headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'Idempotency-Key': key }, body: JSON.stringify(payload) })); }
export const saveAccount = (draft: ManualAccountDraft, signal?: AbortSignal, key?: string) => post('accounts', draft.portfolioId, { ...(draft.accountId.trim() ? { accountId: draft.accountId.trim() } : {}), institution: draft.institution.trim(), accountType: draft.accountType, currency: draft.currency.trim().toUpperCase(), sourceName: draft.sourceName.trim() || null, userAlias: draft.userAlias.trim() || null, custodianOrDp: draft.custodianOrDp.trim() || null, executionBroker: draft.executionBroker.trim() || null, maskedIdentifier: draft.maskedIdentifier.trim() || null, manualHistoryComplete: draft.manualHistoryComplete === true, expectedRevision: draft.expectedRevision ?? null }, signal, key);
export const saveOpeningHolding = (draft: OpeningHoldingDraft, signal?: AbortSignal, key?: string) => post('opening-holdings', draft.portfolioId, { ...(draft.factId.trim() ? { factId: draft.factId.trim() } : {}), accountId: draft.accountId, instrumentName: draft.instrumentName.trim(), isin: draft.isin.trim() || null, quantity: draft.quantity, asOf: draft.asOf, currency: draft.currency.trim().toUpperCase(), documentedCost: draft.documentedCost.trim() || null, ...(draft.expectedRevision != null ? { expectedRevision: draft.expectedRevision } : {}) }, signal, key);
export const saveCashFlow = (draft: CashFlowDraft, signal?: AbortSignal, key?: string) => post('cash-flows', draft.portfolioId, { ...(draft.factId.trim() ? { factId: draft.factId.trim() } : {}), accountId: draft.accountId, effectiveDate: draft.effectiveDate, amount: draft.amount, currency: draft.currency.trim().toUpperCase(), flowType: draft.flowType, note: draft.note.trim() || null, ...(draft.expectedRevision != null ? { expectedRevision: draft.expectedRevision } : {}) }, signal, key);
export const voidManualFact = (kind: 'opening-holdings' | 'cash-flows', portfolioId: string, factId: string, expectedRevision: number, signal?: AbortSignal, key?: string) => post(kind, portfolioId, { factId, expectedRevision, void: true }, signal, key);
