"""
Deterministic Sample Statements & RFC 822 Email MIME Payloads
Generates standard forwarded email fixtures for Zerodha, HDFC Sec, CAMS CAS, and Schwab US.
"""

from email.message import EmailMessage
from typing import List, Optional, Tuple


def create_sample_forwarded_email_mime(
    forwarder_email: str,
    original_sender: str,
    subject: str,
    body_text: str,
    attachments: Optional[List[Tuple[str, str, bytes]]] = None,
    message_id: Optional[str] = None,
) -> bytes:
    """
    Constructs a standard RFC 822 MIME multipart forwarded message as generated by Gmail.
    
    attachments: List of (filename, mime_type, payload_bytes)
    """
    msg = EmailMessage()
    msg["From"] = forwarder_email
    msg["To"] = "vault-ingest@moneymoney.internal"
    msg["Subject"] = f"Fwd: {subject}"
    msg["Date"] = "Fri, 14 Aug 2026 10:30:00 +0530"
    msg["Message-ID"] = message_id or f"<{hash(subject)}@mail.gmail.com>"

    forwarded_header_block = (
        f"---------- Forwarded message ---------\n"
        f"From: {original_sender}\n"
        f"Date: Fri, Aug 14, 2026 at 10:15 AM\n"
        f"Subject: {subject}\n"
        f"To: <{forwarder_email}>\n\n"
    )

    full_body = forwarded_header_block + body_text
    msg.set_content(full_body)

    if attachments:
        for filename, mime_type, data in attachments:
            maintype, subtype = mime_type.split("/", 1)
            msg.add_attachment(
                data,
                maintype=maintype,
                subtype=subtype,
                filename=filename,
            )

    return msg.as_bytes()


def create_direct_broker_email_mime(
    broker_sender: str,
    recipient_email: str,
    subject: str,
    body_text: str,
    attachments: Optional[List[Tuple[str, str, bytes]]] = None,
) -> bytes:
    """Constructs a direct broker inbound email without forwarding wrapper."""
    msg = EmailMessage()
    msg["From"] = broker_sender
    msg["To"] = recipient_email
    msg["Subject"] = subject
    msg["Date"] = "Fri, 14 Aug 2026 09:00:00 +0530"
    msg["Message-ID"] = f"<{hash(subject + broker_sender)}@broker.com>"
    msg.set_content(body_text)

    if attachments:
        for filename, mime_type, data in attachments:
            maintype, subtype = mime_type.split("/", 1)
            msg.add_attachment(
                data,
                maintype=maintype,
                subtype=subtype,
                filename=filename,
            )

    return msg.as_bytes()


# Sample dummy payloads for PDF and CSV attachments (valid byte headers)
SAMPLE_PDF_HEADER = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj\n<< /Title (Contract Note) >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF"
SAMPLE_CSV_CONTENT = b"Date,Action,Symbol,Description,Quantity,Price,Fees & Comm,Amount\n08/14/2026,Buy,NVDA,NVIDIA CORP,10,120.00,0.00,-1200.00\n"

# Standard Fixture Payloads
MIME_ZERODHA_FORWARDED_PRIMARY = create_sample_forwarded_email_mime(
    forwarder_email="alex.taylor@example.com",
    original_sender="Zerodha Broking <contracts@zerodha.com>",
    subject="Contract Note for Trade Date 14-08-2026 - KLMNO9012P",
    body_text="Dear Alex Taylor, please find attached your electronic contract note for trades on 14-08-2026. Password is your PAN.",
    attachments=[("CN20260814_KLMNO9012P.pdf", "application/pdf", SAMPLE_PDF_HEADER)],
)

MIME_HDFC_FORWARDED_FATHER = create_sample_forwarded_email_mime(
    forwarder_email="robert.taylor@example.com",
    original_sender="HDFC Securities <customercare@hdfcsec.com>",
    subject="Contract Note Cum Tax Invoice for Settlement 2026115 - ABCDE1234F",
    body_text="Dear Robert Taylor, please find attached your contract note for settlement 2026115. Password is your PAN or DOB.",
    attachments=[("HDFC_CN_ABCDE1234F.pdf", "application/pdf", SAMPLE_PDF_HEADER)],
)

MIME_CAMS_FORWARDED_MOTHER = create_sample_forwarded_email_mime(
    forwarder_email="margaret.taylor@example.com",
    original_sender="CAMS Mail Services <donotreply@camsonline.com>",
    subject="Consolidated Account Statement - CAMS CAS - FGHIJ5678K",
    body_text="Dear Margaret Taylor, attached is your monthly e-CAS summary for July 2026. Password is your PAN.",
    attachments=[("CAMS_CAS_JUL2026.pdf", "application/pdf", SAMPLE_PDF_HEADER)],
)

MIME_SCHWAB_FORWARDED_PRIMARY = create_sample_forwarded_email_mime(
    forwarder_email="alex.taylor@example.com",
    original_sender="Charles Schwab <statements@schwab.com>",
    subject="Your Charles Schwab Monthly Activity Statement / Export",
    body_text="Dear Alex, your trading activity CSV export for account ending in 8821 is attached.",
    attachments=[("Schwab_Trades_202608.csv", "text/csv", SAMPLE_CSV_CONTENT)],
)

MIME_HUF_FORWARDED_PRIMARY = create_sample_forwarded_email_mime(
    forwarder_email="alex.taylor@example.com",
    original_sender="KFintech Statement Service <cas@kfintech.com>",
    subject="Mutual Fund e-CAS for Taylor Family Trust - PQRST3456Q",
    body_text="Dear Karta, please find attached the HUF portfolio consolidated statement for PAN PQRST3456Q.",
    attachments=[("KFIN_HUF_CAS.pdf", "application/pdf", SAMPLE_PDF_HEADER)],
)
